---
- name: 'Execute two commands on localhost'
  hosts: localhost
  become: yes
  tasks:
    - name: 'Execute a date command'
      command: date
    - name: 'Task to display nameservers'
      command: cat /etc/resolv.conf
