---
- name: 'hosts'
  hosts: all
  become: yes
  tasks:
    - name: 'Execute a script'
      script: '/tmp/install_script.sh'
    
    - name: 'start httpd'
      service:
        name: 'httpd'
        state: 'started'
