#Create a playbook called package.yml under /home/bob/playbooks/ directory to install vim-enhanced package on student-node.

---
- name: 'Install the required package'
  hosts: localhost
  become: yes
  connection: local
  tasks:
    - yum: 
        name: vim-enhanced
        state: present
